### ISSUE TITLE
LTP GET endpoint missing !

### ISSUE THREAD

**Issue by Pranav-Shinde** [dhan-oss/DhanHQ-py#18]
The issue with the websockets is that it runs on it own thread and then we have to go into the complexities of threads management and inter-thread communication to get the LTP and pass on to the another program that expects the LTP to calculate the live PNL or to run a algo script.
If we have a LTP as an GET enpoint, a simple program that can go on executing and whenever it requires the LTP for a particular script, it can simply hit the GET endpoint and continue its execution.
All brokers are providing this endpoint, I am not sure why such a Advanced broker like DHAN doesn't provide it despite of lots of request in the forum.

**Comment by dhan-oss** [comment]
Hello @Pranav-Shinde 
It is on roadmap. We took up websockets over REST APIs as preferred mode for data like Live Market Feed, due to the dynamic nature of price. If you have any further feedback or requests, you can send us at [feedback@dhan.co](mailto:feedback@dhan.co) or join [MadeforTrade Community](https://madefortrade.in/).
